blank_issues_enabled: false
contact_links:
  - name: Report an issue
    url: https://github.com/wouterrutgers/gim-hub.com/issues/new/choose
    about: Report bugs and request features for the website or RuneLite plugin in the GIM Hub website repository.
