/*
 * BSD 2-Clause License
 *
 * Copyright 2022 Thource
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package gimhub.items.containers;

import java.util.List;
import java.util.Map;
import net.runelite.api.gameval.ItemID;

final class ChuggingBarrelPotions {
    private ChuggingBarrelPotions() {}

    static final Map<String, Integer> BY_NAME = Map.ofEntries(
            Map.entry("Agility potion(1)", ItemID._1DOSE1AGILITY),
            Map.entry("Ancient brew(1)", ItemID._1DOSEANCIENTBREW),
            Map.entry("Anti-venom(1)", ItemID.ANTIVENOM1),
            Map.entry("Anti-venom+(1)", ItemID.ANTIVENOM_1),
            Map.entry("Antidote+(1)", ItemID.ANTIDOTE_1),
            Map.entry("Antidote++(1)", ItemID.ANTIDOTE__1),
            Map.entry("Antifire potion(1)", ItemID._1DOSE1ANTIDRAGON),
            Map.entry("Antipoison(1)", ItemID._1DOSEANTIPOISON),
            Map.entry("Attack potion(1)", ItemID._1DOSE1ATTACK),
            Map.entry("Battlemage potion(1)", ItemID._1DOSEBATTLEMAGE),
            Map.entry("Bastion potion(1)", ItemID._1DOSEBASTION),
            Map.entry("Blighted super restore(1)", ItemID.BLIGHTED_1DOSE2RESTORE),
            Map.entry("Combat potion(1)", ItemID._1DOSECOMBAT),
            Map.entry("Defence potion(1)", ItemID._1DOSE1DEFENSE),
            Map.entry("Divine bastion potion(1)", ItemID._1DOSEDIVINEBASTION),
            Map.entry("Divine battlemage potion(1)", ItemID._1DOSEDIVINEBATTLEMAGE),
            Map.entry("Divine magic potion(1)", ItemID._1DOSEDIVINEMAGIC),
            Map.entry("Divine ranging potion(1)", ItemID._1DOSEDIVINERANGE),
            Map.entry("Divine super attack potion(1)", ItemID._1DOSEDIVINEATTACK),
            Map.entry("Divine super combat potion(1)", ItemID._1DOSEDIVINECOMBAT),
            Map.entry("Divine super defence potion(1)", ItemID._1DOSEDIVINEDEFENCE),
            Map.entry("Divine super strength potion(1)", ItemID._1DOSEDIVINESTRENGTH),
            Map.entry("Energy potion(1)", ItemID._1DOSE1ENERGY),
            Map.entry("Extended anti-venom+(1)", ItemID.EXTENDED_ANTIVENOM_1),
            Map.entry("Extended antifire(1)", ItemID._1DOSE2ANTIDRAGON),
            Map.entry("Extended super antifire(1)", ItemID._1DOSE4ANTIDRAGON),
            Map.entry("Fishing potion(1)", ItemID._1DOSEFISHERSPOTION),
            Map.entry("Forgotten brew(1)", ItemID._1DOSEFORGOTTENBREW),
            Map.entry("Goading potion(1)", ItemID._1DOSEGOADING),
            Map.entry("Hunter potion(1)", ItemID._1DOSEHUNTING),
            Map.entry("Magic essence(1)", ItemID._1DOSEMAGICESS),
            Map.entry("Magic potion(1)", ItemID._1DOSE1MAGIC),
            Map.entry("Menaphite remedy(1)", ItemID._1DOSESTATRENEWAL),
            Map.entry("Prayer potion(1)", ItemID._1DOSEPRAYERRESTORE),
            Map.entry("Prayer regeneration potion(1)", ItemID._1DOSE1PRAYER_REGENERATION),
            Map.entry("Ranging potion(1)", ItemID._1DOSERANGERSPOTION),
            Map.entry("Relicym's balm(1)", ItemID.RELICYMS_BALM1),
            Map.entry("Restore potion(1)", ItemID._1DOSESTATRESTORE),
            Map.entry("Sanfew serum(1)", ItemID.SANFEW_SALVE_1_DOSE),
            Map.entry("Saradomin brew(1)", ItemID._1DOSEPOTIONOFSARADOMIN),
            Map.entry("Stamina potion(1)", ItemID._1DOSESTAMINA),
            Map.entry("Strength potion(1)", ItemID._1DOSE1STRENGTH),
            Map.entry("Super antifire potion(1)", ItemID._1DOSE3ANTIDRAGON),
            Map.entry("Super attack(1)", ItemID._1DOSE2ATTACK),
            Map.entry("Super combat potion(1)", ItemID._1DOSE2COMBAT),
            Map.entry("Super defence(1)", ItemID._1DOSE2DEFENSE),
            Map.entry("Super energy(1)", ItemID._1DOSE2ENERGY),
            Map.entry("Super restore(1)", ItemID._1DOSE2RESTORE),
            Map.entry("Super strength(1)", ItemID._1DOSE2STRENGTH),
            Map.entry("Superantipoison(1)", ItemID._1DOSE2ANTIPOISON),
            Map.entry("Surge potion(1)", ItemID._1DOSESURGE),
            Map.entry("Zamorak brew(1)", ItemID._1DOSEPOTIONOFZAMORAK),
            Map.entry("Agility mix(1)", ItemID.BRUTAL_1DOSE1AGILITY),
            Map.entry("Ancient mix(1)", ItemID.BRUTAL_1DOSEANCIENTBREW),
            Map.entry("Antifire mix(1)", ItemID.BRUTAL_1DOSE1ANTIDRAGON),
            Map.entry("Antipoison mix(1)", ItemID.BRUTAL_1DOSEANTIPOISON),
            Map.entry("Antidote+ mix(1)", ItemID.BRUTAL_ANTIDOTE_1),
            Map.entry("Attack mix(1)", ItemID.BRUTAL_1DOSE1ATTACK),
            Map.entry("Combat mix(1)", ItemID.BRUTAL_1DOSECOMBAT),
            Map.entry("Defence mix(1)", ItemID.BRUTAL_1DOSE1DEFENSE),
            Map.entry("Energy mix(1)", ItemID.BRUTAL_1DOSE1ENERGY),
            Map.entry("Extended antifire mix(1)", ItemID.BRUTAL_1DOSE2ANTIDRAGON),
            Map.entry("Extended super antifire mix(1)", ItemID.BRUTAL_1DOSE4ANTIDRAGON),
            Map.entry("Fishing mix(1)", ItemID.BRUTAL_1DOSEFISHERSPOTION),
            Map.entry("Hunting mix(1)", ItemID.BRUTAL_1DOSE1HUNTING),
            Map.entry("Magic essence mix(1)", ItemID.BRUTAL_1DOSEMAGICESS),
            Map.entry("Magic mix(1)", ItemID.BRUTAL_1DOSE1MAGIC),
            Map.entry("Prayer mix(1)", ItemID.BRUTAL_1DOSEPRAYERRESTORE),
            Map.entry("Ranging mix(1)", ItemID.BRUTAL_1DOSERANGERSPOTION),
            Map.entry("Restore mix(1)", ItemID.BRUTAL_1DOSESTATRESTORE),
            Map.entry("Stamina mix(1)", ItemID.BRUTAL_1DOSESTAMINA),
            Map.entry("Strength mix(1)", ItemID.BRUTAL_1DOSE1STRENGTH),
            Map.entry("Super antifire mix(1)", ItemID.BRUTAL_1DOSE3ANTIDRAGON),
            Map.entry("Superattack mix(1)", ItemID.BRUTAL_1DOSE2ATTACK),
            Map.entry("Super def. mix(1)", ItemID.BRUTAL_1DOSE2DEFENSE),
            Map.entry("Super energy mix(1)", ItemID.BRUTAL_1DOSE2ENERGY),
            Map.entry("Super restore mix(1)", ItemID.BRUTAL_1DOSE2RESTORE),
            Map.entry("Super str. mix(1)", ItemID.BRUTAL_1DOSE2STRENGTH),
            Map.entry("Anti-poison supermix(1)", ItemID.BRUTAL_1DOSE2ANTIPOISON),
            Map.entry("Zamorak mix(1)", ItemID.BRUTAL_1DOSEPOTIONOFZAMORAK),
            Map.entry("Relicym's mix(1)", ItemID.BRUTAL_RELICYMS_BALM1));

    static final Map<String, List<Integer>> BY_DRINK_MESSAGE = Map.ofEntries(
            Map.entry("agility potion", List.of(ItemID._1DOSE1AGILITY)),
            Map.entry(
                    "foul liquid",
                    List.of(
                            ItemID._1DOSEANCIENTBREW,
                            ItemID._1DOSEFORGOTTENBREW,
                            ItemID._1DOSEPOTIONOFSARADOMIN,
                            ItemID._1DOSEPOTIONOFZAMORAK)),
            Map.entry("antivenom potion", List.of(ItemID.ANTIVENOM1)),
            Map.entry("super antivenom+ potion", List.of(ItemID.ANTIVENOM_1)),
            Map.entry(
                    "antipoison potion",
                    List.of(ItemID.ANTIDOTE_1, ItemID.ANTIDOTE__1, ItemID._1DOSEANTIPOISON, ItemID._1DOSE2ANTIPOISON)),
            Map.entry("antifire potion", List.of(ItemID._1DOSE1ANTIDRAGON)),
            Map.entry("attack potion", List.of(ItemID._1DOSE1ATTACK, ItemID._1DOSE2ATTACK)),
            Map.entry("battlemage potion", List.of(ItemID._1DOSEBATTLEMAGE)),
            Map.entry("bastion potion", List.of(ItemID._1DOSEBASTION)),
            Map.entry("blighted super restore potion", List.of(ItemID.BLIGHTED_1DOSE2RESTORE)),
            Map.entry("combat potion", List.of(ItemID._1DOSECOMBAT)),
            Map.entry("defence potion", List.of(ItemID._1DOSE1DEFENSE, ItemID._1DOSE2DEFENSE)),
            Map.entry("divine bastion potion", List.of(ItemID._1DOSEDIVINEBASTION)),
            Map.entry("divine battlemage potion", List.of(ItemID._1DOSEDIVINEBATTLEMAGE)),
            Map.entry("divine magic potion", List.of(ItemID._1DOSEDIVINEMAGIC)),
            Map.entry("divine ranging potion", List.of(ItemID._1DOSEDIVINERANGE)),
            Map.entry("divine super attack potion", List.of(ItemID._1DOSEDIVINEATTACK)),
            Map.entry("divine combat potion", List.of(ItemID._1DOSEDIVINECOMBAT)),
            Map.entry("divine super defence potion", List.of(ItemID._1DOSEDIVINEDEFENCE)),
            Map.entry("divine super strength potion", List.of(ItemID._1DOSEDIVINESTRENGTH)),
            Map.entry("energy potion", List.of(ItemID._1DOSE1ENERGY)),
            Map.entry("extended super antivenom+ potion", List.of(ItemID.EXTENDED_ANTIVENOM_1)),
            Map.entry("extended antifire potion", List.of(ItemID._1DOSE2ANTIDRAGON)),
            Map.entry("extended super antifire potion", List.of(ItemID._1DOSE4ANTIDRAGON)),
            Map.entry("fishing potion", List.of(ItemID._1DOSEFISHERSPOTION)),
            Map.entry("goading potion", List.of(ItemID._1DOSEGOADING)),
            Map.entry("Hunter potion", List.of(ItemID._1DOSEHUNTING)),
            Map.entry("potion of magic essence", List.of(ItemID._1DOSEMAGICESS)),
            Map.entry("magic potion", List.of(ItemID._1DOSE1MAGIC)),
            Map.entry("Menaphite remedy", List.of(ItemID._1DOSESTATRENEWAL)),
            Map.entry("restore prayer potion", List.of(ItemID._1DOSEPRAYERRESTORE)),
            Map.entry("prayer regeneration potion", List.of(ItemID._1DOSE1PRAYER_REGENERATION)),
            Map.entry("ranging potion", List.of(ItemID._1DOSERANGERSPOTION)),
            Map.entry("Relicym's Balm", List.of(ItemID.RELICYMS_BALM1)),
            Map.entry("stat restoration potion", List.of(ItemID._1DOSESTATRESTORE)),
            Map.entry("Sanfew Serum", List.of(ItemID.SANFEW_SALVE_1_DOSE)),
            Map.entry("stamina potion", List.of(ItemID._1DOSESTAMINA)),
            Map.entry("strength potion", List.of(ItemID._1DOSE1STRENGTH, ItemID._1DOSE2STRENGTH)),
            Map.entry("super antifire potion", List.of(ItemID._1DOSE3ANTIDRAGON)),
            Map.entry("super combat potion", List.of(ItemID._1DOSE2COMBAT)),
            Map.entry("super energy potion", List.of(ItemID._1DOSE2ENERGY)),
            Map.entry("super restore potion", List.of(ItemID._1DOSE2RESTORE)),
            Map.entry("surge potion", List.of(ItemID._1DOSESURGE)),
            Map.entry(
                    "lumpy potion",
                    List.of(
                            ItemID.BRUTAL_1DOSE1AGILITY,
                            ItemID.BRUTAL_1DOSEANCIENTBREW,
                            ItemID.BRUTAL_1DOSE1ANTIDRAGON,
                            ItemID.BRUTAL_1DOSEANTIPOISON,
                            ItemID.BRUTAL_ANTIDOTE_1,
                            ItemID.BRUTAL_1DOSE1ATTACK,
                            ItemID.BRUTAL_1DOSECOMBAT,
                            ItemID.BRUTAL_1DOSE1DEFENSE,
                            ItemID.BRUTAL_1DOSE1ENERGY,
                            ItemID.BRUTAL_1DOSE2ANTIDRAGON,
                            ItemID.BRUTAL_1DOSE4ANTIDRAGON,
                            ItemID.BRUTAL_1DOSEFISHERSPOTION,
                            ItemID.BRUTAL_1DOSE1HUNTING,
                            ItemID.BRUTAL_1DOSEMAGICESS,
                            ItemID.BRUTAL_1DOSE1MAGIC,
                            ItemID.BRUTAL_1DOSEPRAYERRESTORE,
                            ItemID.BRUTAL_1DOSERANGERSPOTION,
                            ItemID.BRUTAL_1DOSESTATRESTORE,
                            ItemID.BRUTAL_1DOSESTAMINA,
                            ItemID.BRUTAL_1DOSE1STRENGTH,
                            ItemID.BRUTAL_1DOSE3ANTIDRAGON,
                            ItemID.BRUTAL_1DOSE2ATTACK,
                            ItemID.BRUTAL_1DOSE2DEFENSE,
                            ItemID.BRUTAL_1DOSE2ENERGY,
                            ItemID.BRUTAL_1DOSE2RESTORE,
                            ItemID.BRUTAL_1DOSE2STRENGTH,
                            ItemID.BRUTAL_1DOSE2ANTIPOISON,
                            ItemID.BRUTAL_1DOSEPOTIONOFZAMORAK,
                            ItemID.BRUTAL_RELICYMS_BALM1)));
}
